#!/usr/bin/env node
/**
 * Import Migration Data to MongoDB
 * 
 * This script imports the JSON files generated by migrate_data.py
 * into the MongoDB database.
 * 
 * Usage:
 *   node import_data.js
 */

require('dotenv').config();
const fs = require('fs');
const path = require('path');
const connectDB = require('./server/config/database');

// Import models
const StudentOfficer = require('./server/models/StudentOfficer');
const Mentor = require('./server/models/Mentor');
const Event = require('./server/models/Event');
const BlogPost = require('./server/models/BlogPost');
const PageBackground = require('./server/models/PageBackground');
const HomeInformation = require('./server/models/HomeInformation');
const AboutSection = require('./server/models/AboutSection');

const MIGRATION_DATA_DIR = './migration_data';

async function importData() {
  try {
    await connectDB();
    console.log('Connected to MongoDB\n');

    // Import Officers
    if (fs.existsSync(path.join(MIGRATION_DATA_DIR, 'officers.json'))) {
      const officers = JSON.parse(
        fs.readFileSync(path.join(MIGRATION_DATA_DIR, 'officers.json'), 'utf8')
      );
      await StudentOfficer.deleteMany({});
      await StudentOfficer.insertMany(officers);
      console.log(`✓ Imported ${officers.length} officers`);
    }

    // Import Mentors
    if (fs.existsSync(path.join(MIGRATION_DATA_DIR, 'mentors.json'))) {
      const mentors = JSON.parse(
        fs.readFileSync(path.join(MIGRATION_DATA_DIR, 'mentors.json'), 'utf8')
      );
      await Mentor.deleteMany({});
      await Mentor.insertMany(mentors);
      console.log(`✓ Imported ${mentors.length} mentors`);
    }

    // Import Events
    if (fs.existsSync(path.join(MIGRATION_DATA_DIR, 'events.json'))) {
      const events = JSON.parse(
        fs.readFileSync(path.join(MIGRATION_DATA_DIR, 'events.json'), 'utf8')
      );
      await Event.deleteMany({});
      await Event.insertMany(events);
      console.log(`✓ Imported ${events.length} events`);
    }

    // Import Blog Posts
    if (fs.existsSync(path.join(MIGRATION_DATA_DIR, 'blog_posts.json'))) {
      const posts = JSON.parse(
        fs.readFileSync(path.join(MIGRATION_DATA_DIR, 'blog_posts.json'), 'utf8')
      );
      await BlogPost.deleteMany({});
      await BlogPost.insertMany(posts);
      console.log(`✓ Imported ${posts.length} blog posts`);
    }

    // Import Page Backgrounds
    if (fs.existsSync(path.join(MIGRATION_DATA_DIR, 'backgrounds.json'))) {
      const backgrounds = JSON.parse(
        fs.readFileSync(path.join(MIGRATION_DATA_DIR, 'backgrounds.json'), 'utf8')
      );
      await PageBackground.deleteMany({});
      await PageBackground.insertMany(backgrounds);
      console.log(`✓ Imported ${backgrounds.length} page backgrounds`);
    }

    // Import Home Information
    if (fs.existsSync(path.join(MIGRATION_DATA_DIR, 'home_info.json'))) {
      const homeInfo = JSON.parse(
        fs.readFileSync(path.join(MIGRATION_DATA_DIR, 'home_info.json'), 'utf8')
      );
      await HomeInformation.deleteMany({});
      await HomeInformation.insertMany(homeInfo);
      console.log(`✓ Imported ${homeInfo.length} home sections`);
    }

    // Import About Sections
    if (fs.existsSync(path.join(MIGRATION_DATA_DIR, 'about_sections.json'))) {
      const aboutSections = JSON.parse(
        fs.readFileSync(path.join(MIGRATION_DATA_DIR, 'about_sections.json'), 'utf8')
      );
      await AboutSection.deleteMany({});
      await AboutSection.insertMany(aboutSections);
      console.log(`✓ Imported ${aboutSections.length} about sections`);
    }

    console.log('\n✓ All data imported successfully!');
    console.log('\nNext steps:');
    console.log('1. Copy media files from Django media/ to server/uploads/');
    console.log('2. Update image paths in the database if needed');
    console.log('3. Test the application');

    process.exit(0);
  } catch (error) {
    console.error('✗ Error importing data:', error);
    process.exit(1);
  }
}

importData();
