# Generated by Django 5.1.6 on 2025-03-01 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='url',
            new_name='registration_link',
        ),
    ]
