# Generated by Django 5.1.2 on 2025-03-03 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home Page'), ('about', 'About Page'), ('blog', 'Blog Page'), ('events', 'Events Page'), ('members', 'Members Page'), ('contact', 'Contact Page')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=500)),
                ('background_image', models.ImageField(upload_to='backgrounds/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page Background',
                'verbose_name_plural': 'Page Backgrounds',
            },
        ),
    ]
