# Generated by Django 5.1.2 on 2025-03-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_mentor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mentor',
        ),
        migrations.AlterModelOptions(
            name='studentofficer',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Student Officer/Mentor', 'verbose_name_plural': 'Student Officers/Mentors'},
        ),
        migrations.AddField(
            model_name='studentofficer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentofficer',
            name='mentor_information',
            field=models.TextField(blank=True, help_text="Information about the mentor's background, expertise, and role"),
        ),
        migrations.AddField(
            model_name='studentofficer',
            name='order',
            field=models.IntegerField(default=0, help_text='Order in which the mentor should appear (lower numbers appear first)'),
        ),
        migrations.AlterField(
            model_name='studentofficer',
            name='email',
            field=models.EmailField(blank=True, max_length=200),
        ),
    ]
