# Generated by Django 5.1.2 on 2025-03-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_delete_mentor_alter_studentofficer_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='mentors')),
                ('linkedin', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=200)),
                ('bio', models.TextField(help_text="Detailed information about the mentor's background and expertise")),
                ('expertise', models.CharField(help_text='Main areas of expertise', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Order in which the mentor should appear (lower numbers appear first)')),
            ],
            options={
                'verbose_name': 'Mentor',
                'verbose_name_plural': 'Mentors',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='studentofficer',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Student Officer', 'verbose_name_plural': 'Student Officers'},
        ),
        migrations.RemoveField(
            model_name='studentofficer',
            name='mentor_information',
        ),
        migrations.AlterField(
            model_name='studentofficer',
            name='order',
            field=models.IntegerField(default=0, help_text='Order in which the officer should appear (lower numbers appear first)'),
        ),
    ]
