# Generated by Django 5.1.2 on 2025-03-18 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_mentor_alter_studentofficer_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('video_link', 'Video Link')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about_images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='about_videos/')),
                ('video_link', models.URLField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
