# Generated by Django 5.1.2 on 2025-03-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_aboutsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='is_homepage_feature',
            field=models.BooleanField(default=False, help_text='Feature this section on the homepage'),
        ),
    ]
