# Generated by Django 5.1.2 on 2025-03-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_aboutsection_is_active_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutSection',
        ),
        migrations.AddField(
            model_name='mentor',
            name='google_scholar',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='personal_website',
            field=models.URLField(blank=True),
        ),
    ]
