# Generated by Django 5.1.2 on 2025-03-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_homeinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeinformation',
            name='section_type',
            field=models.CharField(choices=[('text_media', 'Text with Media'), ('media_only', 'Media Only')], default='text_media', max_length=20),
        ),
        migrations.AlterField(
            model_name='homeinformation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
