# Generated by Django 5.1.2 on 2025-03-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_homeinformation_section_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Mission', max_length=200)),
                ('content', models.TextField(help_text='Main content for the mission section')),
                ('image', models.ImageField(blank=True, help_text='Optional image for the mission section', null=True, upload_to='mission')),
                ('button_text', models.CharField(blank=True, help_text='Optional button text (leave empty for no button)', max_length=50, null=True)),
                ('button_url', models.URLField(blank=True, help_text='URL for the button if button text is provided', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Only one mission section should be active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mission Section',
                'verbose_name_plural': 'Mission Section',
            },
        ),
    ]
